const app=document.querySelector('#app');
const S={screen:'home',names:['Alex','Bela','Cem','Daria','Elif','Finn'],roles:[],show:0,missions:0,score:0,answers:[],votes:{},time:0,timer:null};
const missions=[
 {room:'Archiv',icon:'🗄️',title:'Akte 1: Woher kommt „gut“?',prompt:'Welche Aussage trifft Nietzsches genealogische Methode am ehesten?',choices:['Moralbegriffe sind zeitlose Wahrheiten.','Moralbegriffe haben eine Geschichte und entstehen in Macht- und Deutungskämpfen.','Moral ist nur eine Frage des persönlichen Geschmacks.'],correct:1,explain:'Genealogie behandelt Moral nicht als selbstverständlich, sondern fragt nach Entstehungsbedingungen, Interessen und Wertverschiebungen.'},
 {room:'Wertelabor',icon:'⚗️',title:'Akte 2: Zwei Wertungsweisen',prompt:'Welche Zuordnung passt zur ersten Abhandlung?',choices:['Vornehm: gut/schlecht; ressentimentgeprägt: gut/böse.','Vornehm: gut/böse; ressentimentgeprägt: wahr/falsch.','Beide Wertungsweisen meinen dasselbe.'],correct:0,explain:'Nietzsche kontrastiert die vornehme Selbstbejahung „gut/schlecht“ mit der reaktiven Umwertung „gut/böse“. Das ist Analyse seiner Argumentation, keine Zustimmung.'},
 {room:'Schuldkammer',icon:'⛓️',title:'Akte 3: Schuld und Gedächtnis',prompt:'Welche Entwicklung rekonstruiert Nietzsche?',choices:['„Schuld“ entstand ausschließlich durch Religion.','Aus dem Verhältnis von Gläubiger und Schuldner werden Pflicht, Gedächtnis und später moralische Schuld gedeutet.','Schlechtes Gewissen ist angeboren.'],correct:1,explain:'Nietzsche verbindet Schuld zunächst mit dem Schuldnerverhältnis und beschreibt anschließend eine Verinnerlichung von Trieben.'},
 {room:'Observatorium',icon:'🔭',title:'Akte 4: Kritik prüfen',prompt:'Welche kritische Rückfrage ist philosophisch am stärksten?',choices:['Ist Nietzsches historische Erzählung belegt und folgt aus Herkunft schon eine Bewertung?','Warum schreibt Nietzsche so kompliziert?','Darf man alte Texte überhaupt kritisieren?'],correct:0,explain:'Eine gute Prüfung trennt Genese und Geltung: Die Entstehung eines Wertes widerlegt ihn nicht automatisch. Zudem sind Nietzsches historische Behauptungen prüfbar.'}
];
function save(){localStorage.setItem('moralstation',JSON.stringify({...S,timer:null}))}
function view(html){app.innerHTML=html;scrollTo(0,0)}
function home(){clearInterval(S.timer);view(`<section class="panel hero"><div class="eyebrow">Philosophie EF · Mission für 6</div><h1>Moralstation<br>GEN-1887</h1><p class="quote">Nicht nur fragen: „Was ist gut?“, sondern: Wie wurden unsere Werte zu Werten?</p><div class="grid"><div class="card"><b>1 iPad · 6 Personen</b><p class="small">Pass-and-play. Rollen bleiben geheim. Keine Anmeldung, keine Datenübertragung.</p></div><div class="card"><b>ca. 45–60 Minuten</b><p class="small">Rollen, vier Akten, Notfallkonferenz, Sicherung.</p></div></div><p class="alert"><b>Hinweis:</b> Eigenständiges Unterrichtsspiel im Social-Deduction-Stil. Keine offiziellen Grafiken oder Spielinhalte.</p><button onclick="setup()">Mission starten</button><button class="secondary" onclick="teacher()">Lehrkraft-Modus</button></section>`)}
function setup(){S.screen='setup';view(`<section class="panel"><div class="eyebrow">Crew registrieren</div><h2>Sechs Codenamen</h2><p>Ein iPad wandert gleich verdeckt durch die Gruppe. Jede Person sieht nur die eigene Rollenkarte.</p>${S.names.map((n,i)=>`<input class="nameinput" aria-label="Name ${i+1}" value="${n}" oninput="S.names[${i}]=this.value">`).join('')}<br><button onclick="deal()">Rollen auslosen</button><button class="secondary" onclick="home()">Zurück</button></section>`)}
function deal(){let bad=Math.floor(Math.random()*6);S.roles=S.names.map((n,i)=>i===bad?'Agent des Ressentiments':'Genealogische Crew');S.show=0;S.missions=0;S.score=0;S.answers=[];S.votes={};passCard()}
function passCard(){let n=S.names[S.show];view(`<section class="panel hero"><div class="eyebrow">Geheime Übergabe ${S.show+1}/6</div><h2>iPad an <span style="color:var(--cyan)">${esc(n)}</span></h2><p>Alle anderen schauen weg. Tippe erst dann auf „Rolle anzeigen“.</p><button onclick="revealRole()">Rolle anzeigen</button></section>`)}
function revealRole(){let bad=S.roles[S.show].startsWith('Agent');view(`<section class="panel hero reveal ${bad?'danger':'success'}"><div class="eyebrow">Nur für ${esc(S.names[S.show])}</div><div class="bigrole ${bad?'bad':''}">${S.roles[S.show]}</div>${bad?`<p><b>Geheimauftrag:</b> Bringe die Gruppe bei mindestens zwei Akten zu einer plausibel klingenden, aber unhistorischen oder vorschnellen Antwort. Du darfst argumentieren, aber keine Regeln brechen und keine falschen Zitate erfinden.</p>`:`<p><b>Auftrag:</b> Rekonstruiert Nietzsches Argumente sauber. Achtet auf historische Entstehung, Perspektive und den Unterschied zwischen Beschreibung und Zustimmung.</p>`}<button onclick="nextRole()">Rolle verbergen & weiter</button></section>`)}
function nextRole(){S.show++;if(S.show<6)passCard();else briefing()}
function briefing(){view(`<section class="panel"><div class="eyebrow">Briefing</div><h2>Die Moralstation ist infiltriert.</h2><p>Bearbeitet vier Akten. Diskutiert jeweils <b>maximal 4 Minuten</b>. Eine Person bedient das iPad, alle müssen mindestens einmal begründen.</p><div class="alert">Der Agent darf Zweifel säen, aber keine Textzitate erfinden. Die Crew gewinnt fachlich durch begründete Antworten, nicht bloß durch Enttarnung.</div><button onclick="startMission()">Akte 1 öffnen</button></section>`)}
function startMission(){S.time=4*60;runTimer();renderMission()}
function runTimer(){clearInterval(S.timer);S.timer=setInterval(()=>{S.time=Math.max(0,S.time-1);let t=document.querySelector('.timer');if(t)t.textContent=fmt(S.time);if(!S.time)clearInterval(S.timer)},1000)}
function renderMission(){let m=missions[S.missions];view(`<section class="panel"><div class="topbar"><span class="tag">${m.icon} ${m.room}</span><span class="timer">${fmt(S.time)}</span></div><div class="progress"><div style="width:${S.missions/4*100}%"></div></div><h2>${m.title}</h2><p class="quote">${m.prompt}</p><div>${m.choices.map((c,i)=>`<button class="choice" onclick="answer(${i})">${String.fromCharCode(65+i)} · ${c}</button>`).join('')}</div><p class="small">Regel: Erst abstimmen, dann tippen. Nennt mindestens einen Grund und einen möglichen Einwand.</p></section>`)}
function answer(i){clearInterval(S.timer);let m=missions[S.missions],ok=i===m.correct;S.answers.push({i,ok});if(ok)S.score++;view(`<section class="panel ${ok?'success':'danger'}"><div class="eyebrow">Systemprüfung</div><h2>${ok?'Akte stabilisiert':'Fehlkopplung entdeckt'}</h2><p>${m.explain}</p><div class="card"><b>Mini-Sicherung</b><p>Formuliert gemeinsam einen Satz: „Nietzsche behauptet hier, dass …“ Eine andere Person ergänzt: „Dagegen könnte man einwenden, dass …“</p></div><button onclick="advance()">${S.missions<3?'Nächste Akte':'Notfallkonferenz'}</button></section>`)}
function advance(){S.missions++;if(S.missions<4){S.time=240;runTimer();renderMission()}else meeting()}
function meeting(){S.time=300;runTimer();view(`<section class="panel"><div class="topbar"><div><div class="eyebrow">Notfallkonferenz</div><h2>Wer manipulierte die Deutungen?</h2></div><span class="timer">${fmt(S.time)}</span></div><p>Jede Person erhält <b>45 Sekunden</b>: Verdacht plus fachlichen Beleg. Danach stimmt die Gruppe einmal ab.</p><div class="grid votegrid">${S.names.map((n,i)=>`<button class="secondary" onclick="finish(${i})">${esc(n)}</button>`).join('')}</div><p class="small">Nicht Ausstrahlung bewerten, sondern Gesprächsbeiträge: Wer drängte zu zeitlosen, unbegründeten oder vorschnellen Deutungen?</p></section>`)}
function finish(i){clearInterval(S.timer);let agent=S.roles.indexOf('Agent des Ressentiments'),caught=i===agent;view(`<section class="panel"><div class="eyebrow">Missionsprotokoll</div><h2>${caught?'Agent identifiziert':'Agent blieb unentdeckt'}</h2><p>Der Agent war <b style="color:var(--red)">${esc(S.names[agent])}</b>. Fachscore: <b>${S.score}/4</b>.</p><div class="grid"><div class="card"><h3>Exit-Ticket</h3><ol><li>Erkläre „Genealogie“ in einem Satz.</li><li>Nenne eine Wertverschiebung aus der ersten Abhandlung.</li><li>Formuliere eine Kritik an Nietzsches Vorgehen.</li></ol></div><div class="card"><h3>Urteil</h3><p>Vervollständigt: „Nietzsches Genealogie macht Moral fragwürdig, aber nicht automatisch ungültig, weil …“</p></div></div><button onclick="home()">Neue Mission</button></section>`)}
function teacher(){view(`<section class="panel"><div class="eyebrow">Lehrkraft-Modus</div><h2>Unterrichtsrahmen EF NRW</h2><div class="grid"><div class="card"><h3>Lernziel</h3><p>Die Lernenden rekonstruieren zentrale genealogische Argumente, unterscheiden Genese und Geltung und beurteilen Nietzsches Verfahren.</p></div><div class="card"><h3>Kompetenzfokus</h3><p>Sachkompetenz: Position rekonstruieren. Methodenkompetenz: Begriffe und Argumente analysieren. Urteilskompetenz: Tragfähigkeit prüfen. Handlungskompetenz: kooperativ vertreten.</p></div></div><h3>60-Minuten-Ablauf</h3><ol><li><b>0–5:</b> provokanter Einstieg: „Sind Werte entdeckt oder gemacht?“</li><li><b>5–12:</b> Rollen und Briefing.</li><li><b>12–36:</b> vier Akten, je ca. 6 Minuten.</li><li><b>36–44:</b> Notfallkonferenz.</li><li><b>44–55:</b> fachliche Auswertung, Genese ≠ Geltung.</li><li><b>55–60:</b> Exit-Ticket.</li></ol><div class="alert"><b>Didaktische Leitplanke:</b> „Herren-“ und „Sklavenmoral“ als Begriffe in Nietzsches Diagnose behandeln, nicht als Rollenetiketten für Lernende. Diskriminierende Übertragungen sofort stoppen.</div><h3>Vorentlastung</h3><p>Hilfreich ist ein kurzer Auszug aus der ersten Abhandlung, besonders die Unterscheidung „gut/schlecht“ und „gut/böse“. Die App ersetzt nicht die Textarbeit, sondern strukturiert Rekonstruktion und Kritik.</p><button onclick="home()">Zur Startseite</button></section>`)}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]))}
home();
